# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5725769fd1ac8dc29d8602846d911cd11d37d8a316b2950c56bb91e94ed2cce23321fa8279a75a13387751b7b7fa18e189b67adf587ae6e89694c45f9bf8fd8e

test:
  secret_key_base: ee2aecd206cc980b2d1a7d0c1c46f88876cf8768d5524c6969363fdd3b48eede8aa0da89f66d38fad1296a70ecf43e556869b16847a9c22384946977fdd708a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
